function New-HealthReport {
    param([hashtable]$HealthData)

    $html = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>PC Health Report - $($HealthData.ComputerName)</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; background: #f0f2f5; color: #333; }
        .container { max-width: 1100px; margin: 30px auto; background: white; padding: 25px; border-radius: 12px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
        h1 { color: #0078D4; text-align: center; border-bottom: 3px solid #0078D4; padding-bottom: 10px; }
        .score-circle {
            width: 160px; height: 160px; border-radius: 50%; margin: 20px auto; display: flex; 
            align-items: center; justify-content: center; font-size: 48px; font-weight: bold;
            border: 14px solid $(if($HealthData.HealthScore -ge 75){'#28a745'}elseif($HealthData.HealthScore -ge 60){'#ffc107'}else{'#dc3545'});
        }
        .section { margin: 25px 0; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #0078D4; color: white; }
        .good { color: #28a745; font-weight: bold; }
        .warning { color: #ffc107; font-weight: bold; }
        .critical { color: #dc3545; font-weight: bold; }
        .footer { text-align: center; margin-top: 40px; color: #666; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🖥️ PC Health Check Report</h1>
        <p style="text-align:center;"><strong>Computer:</strong> $($HealthData.ComputerName) | <strong>Date:</strong> $($HealthData.CheckDate)</p>

        <div class="score-circle">$($HealthData.HealthScore)</div>
        <h2 style="text-align:center;">Overall Health Score</h2>

        <div class="section">
            <h2>📊 Performance</h2>
            <table>
                <tr><th>Metric</th><th>Value</th><th>Status</th></tr>
                <tr><td>CPU Usage</td><td>$($HealthData.CPU.AvgUsage)%</td><td class="$(if($HealthData.CPU.AvgUsage -gt 70){'critical'}else{'good'})">$(if($HealthData.CPU.AvgUsage -gt 70){'High'}else{'Normal'})</td></tr>
                <tr><td>Memory Usage</td><td>$($HealthData.Memory.UsagePercent)%</td><td class="$(if($HealthData.Memory.UsagePercent -gt 80){'critical'}else{'good'})">$(if($HealthData.Memory.UsagePercent -gt 80){'High'}else{'Normal'})</td></tr>
                <tr><td>Uptime</td><td>$($HealthData.Uptime.UptimeDays) days</td><td class="good">OK</td></tr>
            </table>
        </div>

        <div class="section">
            <h2>💾 Disk Health</h2>
            $(($HealthData.Disk | ForEach-Object { 
                "<p><strong>$($_.Drive)</strong>: $($_.FreeSpacePercent)% free — <span class=`"$($_.Health.ToLower())`">$($_.Health)</span></p>"
            }) -join '')
        </div>

        <div class="section">
            <h2>🔒 Security & Updates</h2>
            <p>Antivirus: $($HealthData.Antivirus.DisplayName) — Real-time Protection: <strong>$(if($HealthData.Antivirus.RealTimeEnabled){'✅ Enabled'}else{'❌ Disabled'})</strong></p>
            <p>Pending Windows Updates: <strong>$($HealthData.Updates.PendingUpdates)</strong></p>
        </div>

        <div class="section">
            <h2>⚠️ Recent Critical Events (Last 7 days)</h2>
            <table>
                <tr><th>Time</th><th>Source</th><th>Message</th></tr>
                $(if($HealthData.EventLogs.Count -gt 0){
                    ($HealthData.EventLogs | ForEach-Object {
                        "<tr><td>$($_.TimeCreated)</td><td>$($_.LogName)</td><td>$($_.Message.Substring(0, [Math]::Min(100, $_.Message.Length)))</td></tr>"
                    }) -join ''
                } else { "<tr><td colspan='3'>No critical errors found in the last 7 days.</td></tr>" })
            </table>
        </div>

        <div class="footer">
            Generated by PCHealthChecker • Automated Helpdesk Tool<br>
            $(Get-Date -Format "yyyy-MM-dd HH:mm")
        </div>
    </div>
</body>
</html>
"@
    return $html
}

Export-ModuleMember -Function *