function New-HealthReport {
    param([hashtable]$HealthData)

    $html = @"
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>PC Health Report - $($HealthData.ComputerName)</title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; margin: 30px; background: #f8f9fa; }
        .container { max-width: 1200px; margin: auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }
        h1 { color: #0078D4; border-bottom: 3px solid #0078D4; padding-bottom: 10px; }
        .score-circle {
            width: 180px; height: 180px; border-radius: 50%; display: flex; align-items: center; justify-content: center; 
            font-size: 52px; font-weight: bold; margin: 20px auto; border: 12px solid #28a745;
        }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; border: 1px solid #dee2e6; text-align: left; }
        th { background: #0078D4; color: white; }
        .good { background: #d4edda; }
        .warning { background: #fff3cd; }
        .critical { background: #f8d7da; }
        .footer { text-align: center; margin-top: 40px; color: #6c757d; font-size: 0.9em; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🖥️ PC Health Check Report</h1>
        <p><strong>Computer:</strong> $($HealthData.ComputerName) | <strong>Date:</strong> $($HealthData.CheckDate)</p>
        
        <div class="score-circle" style="border-color: $(if($HealthData.HealthScore -ge 80){'#28a745'}elseif($HealthData.HealthScore -ge 60){'#ffc107'}else{'#dc3545'})">
            $($HealthData.HealthScore)
        </div>
        <h2 style="text-align:center;">Overall Health Score</h2>

        <h2>📊 Performance</h2>
        <table>
            <tr><th>Component</th><th>Value</th><th>Status</th></tr>
            <tr><td>CPU Usage</td><td>$($HealthData.CPU.AvgUsage)%</td><td class="$(if($HealthData.CPU.AvgUsage -gt 70){'critical'}else{'good'})">$(if($HealthData.CPU.AvgUsage -gt 70){'High'}else{'Normal'})</td></tr>
            <tr><td>Memory Usage</td><td>$($HealthData.Memory.UsagePercent)%</td><td class="$(if($HealthData.Memory.UsagePercent -gt 80){'critical'}else{'good'})">$(if($HealthData.Memory.UsagePercent -gt 80){'High'}else{'Normal'})</td></tr>
            <tr><td>Uptime</td><td>$($HealthData.Uptime.UptimeDays) days</td><td class="good">OK</td></tr>
        </table>

        <h2>💾 Disk Health</h2>
        $(($HealthData.Disk | ForEach-Object { 
            "<p><strong>$($_.Drive)</strong>: $($_.FreeSpacePercent)% free — <strong>$($_.Health)</strong></p>"
        }) -join '')

        <h2>🔒 Security</h2>
        <p>Antivirus: $($HealthData.Antivirus.DisplayName ?? 'Unknown') | Real-time Protection: $(if($HealthData.Antivirus.RealTimeEnabled){'✅ Enabled'}else{'❌ Disabled'})</p>
        <p>Pending Windows Updates: $($HealthData.Updates.PendingUpdates)</p>

        <h2>⚠️ Recent Critical Events (Last 7 days)</h2>
        <table>
            <tr><th>Time</th><th>Source</th><th>Message</th></tr>
            $(($HealthData.EventLogs | ForEach-Object {
                "<tr><td>$($_.TimeCreated)</td><td>$($_.LogName)</td><td>$($_.Message.Substring(0, [Math]::Min(120, $_.Message.Length)))</td></tr>"
            }) -join '')
        </table>

        <div class="footer">
            Generated by PCHealthChecker • Automated Helpdesk Diagnostic Tool<br>
            $(Get-Date)
        </div>
    </div>
</body>
</html>
"@
    return $html
}

Export-ModuleMember -Function *